### ISSUE TITLE
Installation from MELPA doesn't work

### ISSUE THREAD

**Issue by shishini** [Raku/raku-mode#18]
Installation from MELPA doesn't work
I got this error message 
> package-install-from-archive: https://melpa.org/packages/perl6-mode-20161228.430.tar: Not found

I think you need to update melpa with the latest version

**Comment by dantecatalfamo** [comment]
Did you refresh you package list?

**Comment by matiaslina** [comment]
Closing this since now it's `raku-mode`.

Feel free to reopen it if there's some problem installing `raku-mode`
