### ISSUE TITLE
Only first of each group of autoloads is indexed by autoloads file generator

### ISSUE THREAD

**Issue by hlissner** [Raku/raku-mode#33]
See these lines:

https://github.com/Raku/raku-mode/blob/44529c097f98723067f852c6496d91257978c1e2/raku-detect.el#L12-L21

Only the first `autoload` call beneath each `;;;###autoload` is being indexed by Emacs' autoloader. Specifically, the resulting `raku-mode-autoloads.el` looks like this:

```elisp
;;;### (autoloads nil "raku-detect" "raku-detect.el" (0 0 0 0))
;;; Generated autoloads from raku-detect.el

(add-to-list 'interpreter-mode-alist '("perl6" . raku-mode))

(add-to-list 'auto-mode-alist '("\\.p[lm]?6\\'" . raku-mode))

(defconst raku-magic-pattern (rx line-start (0+ space) (or (and "use" (1+ space) "v6") (and (opt (and (or "my" "our") (1+ space))) (or "module" "class" "role" "grammar" "enum" "slang" "subset")))))

(autoload 'raku-magic-matcher "raku-detect" "<snip>" nil nil)

(add-to-list 'magic-mode-alist '(raku-magic-matcher . raku-mode))

;;;***
```

----

To correct this, either prefix each line with `;;;###autoload\n` or `;;;###autoload `, e.g.

```elisp
;;;###autoload (add-to-list 'interpreter-mode-alist '("perl6" . raku-mode))
;;;###autoload (add-to-list 'interpreter-mode-alist '("raku" . raku-mode))

;;;###autoload (add-to-list 'auto-mode-alist '("\\.p[lm]?6\\'" . raku-mode))
;;;###autoload (add-to-list 'auto-mode-alist '("\\.nqp\\'"     . raku-mode))
;;;###autoload (add-to-list 'auto-mode-alist '("\\.raku\\'"    . raku-mode))
;;;###autoload (add-to-list 'auto-mode-alist '("\\.rakumod\\'" . raku-mode))
;;;###autoload (add-to-list 'auto-mode-alist '("\\.rakutest\\'" . raku-mode))
````

Or, alternatively:

```elisp
;;;###autoload
(add-to-list 'interpreter-mode-alist '("perl6\\|raku" . raku-mode))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.p[lm]?6\\'" . raku-mode))
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.nqp\\'" . raku-mode))
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.raku\\(?:mod\\|test\\)?\\'" . raku-mode))
```

**Comment by matiaslina** [comment]
> Only the first autoload call beneath each ;;;###autoload is being indexed by Emacs' autoloader. 

Didn't know that `;;;###autoload` work that way (thinking about it… it makes sense)

> Specifically, the resulting raku-mode-autoloads.el looks like this:

How can I generate that file and where do I find it? It's generated the first time the module it's loaded? (I'm just curious :stuck_out_tongue: )

**Comment by hlissner** [comment]
> How can I generate that file and where do I find it? It's generated the first time the module it's loaded? (I'm just curious stuck_out_tongue )

Emacs generates a PACKAGE-autoloads.el file while it is installed. e.g. `M-x package-install RET raku-mode`, then `M-x find-library RET raku-mode-autoloads`. Emacs loads these autoloads files when you initialize package.el (with a `(package-initialize)` somewhere in your Emacs config).

Anyhow, glad I could help!
