### ISSUE TITLE
Add a git tag for MELPA Stable

### ISSUE THREAD

**Issue by juanfra684** [Raku/raku-mode#38]
The project doesn't have any git tag, so MELPA will never publish the mode in MELPA stable. Could you add a git tag to the repo?.

**Comment by tmtvl** [comment]
.oO(If we are going to start tagging releases for MELPA stable it may also be prudent to switch over to a more git-flow-esque style of managing the repo.)

**Comment by matiaslina** [comment]
I think we can tag it as version `0.1.0` now or after https://github.com/Raku/raku-mode/pull/35 is merged.

After that we should keep the changes/PR on a `devel` branch. That's what you mean with a more git-flow-esque style @tmtvl ?

**Comment by tmtvl** [comment]
I've created the 0.1.0 tag here: https://github.com/Raku/raku-mode/releases/tag/0.1.0
