### ISSUE TITLE
Readme references deprecated flycheck-raku - update to raku/flycheck-raku

### ISSUE THREAD

**Issue by mujo-hash** [Raku/raku-mode#55]
The readme links to https://github.com/widefox/flycheck-raku for flycheck-raku when the current upstream is https://github.com/Raku/flycheck-raku

See https://github.com/widefox/flycheck-raku for details.

**Comment by lizmat** [comment]
Thanks for the report, fixed with https://github.com/Raku/raku-mode/commit/977b14a7c1
