### ISSUE TITLE
How compatible with 2024 Raku?

### ISSUE THREAD

**Issue by welcome-linja** [Raku/raku-mode#61]
I see there was a long gap until two recent commits re. colours, and I'm not intimately familiar with Raku development but I know there's been active work in that time at least on the internals. So, is this mode still accurate for the version of Raku available today?

**Comment by Altai-man** [comment]
It is pretty much accurate.
Raku's syntax has been stable for years and years by now, so no additional support (except for bugfixes etc) is necessary, I would say.

**Comment by welcome-linja** [comment]
Nice. Love a bit of stability.
