### ISSUE TITLE
deploying to melpa

### ISSUE THREAD

**Issue by bradclawsie** [Raku/raku-mode#9]
As far as I can tell, the repo from which this was forked is still that which is downloaded in melpa.

Are there plans to deploy this fork instead?

**Comment by tbrowder** [comment]
On Sat, Jan 21, 2017 at 00:25 brad clawsie <notifications@github.com> wrote:

> As far as I can tell, the repo from which this was forked is still that
> which is downloaded in melpa.
>
>
> Are there plans to deploy this fork instead?
>
  That sounds like a good idea, but  don't know how to do that, nor do I
have the motivation to find out--sorry.

**Comment by bradclawsie** [comment]
I am trying to establish a dialog with the original author to see if there is a way to resolve this

https://github.com/hinrik/perl6-mode/issues/18

**Comment by Altai-man** [comment]
@bradclawsie, actually, to deploy package to melpa we need to follow this instruction: https://github.com/melpa/melpa#recipe-format. It seems not so hard.
The problem is
>Packages should be built from the official package repository. Forks of the official repository will not be accepted except in extreme circumstances.

from the melpa repo documentation.

I don't think it is possible without original author response.

**Comment by bradclawsie** [comment]
I guess I will find out if they have some policy for managing orphaned packages. The original author is unresponsive...I opened an issue on his repo and never heard back.

**Comment by JJ** [comment]
Would changing the name work?

**Comment by treyharris** [comment]
I've inquired, and there's a process. I'm willing to shepherd it through starting immediately if nobody objects (I'll give you until 48 hours from now, Tue 9 May 18:00 UTC). I've created the task lisk I propose in #11.

If that is acceptable, I'll close this issue and we can move further work there.

**Comment by matiaslina** [comment]
Closing this issue since this package is already on MELPA.
